'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class activities
    Public Property id As Integer
    Public Property project_id As Integer
    Public Property name As String
    Public Property comment As String
    Public Property visible As Nullable(Of Short)
    Public Property fixed_rate As Double
    Public Property hourly_rate As Double
    Public Property budget As Nullable(Of Double)
    Public Property time_budget As Nullable(Of Double)
    Public Property color As String

    Public Overridable Property projects As projects
    Public Overridable Property timesheet As ICollection(Of timesheet) = New HashSet(Of timesheet)

End Class
