'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class customers
    Public Property id As Integer
    Public Property name As String
    Public Property number As String
    Public Property comment As String
    Public Property company As String
    Public Property contact As String
    Public Property address As String
    Public Property country As String
    Public Property currency As String
    Public Property phone As String
    Public Property mobile As String
    Public Property email As String
    Public Property fixed_rate As Double
    Public Property hourly_rate As Double
    Public Property budget As Nullable(Of Double)
    Public Property time_budget As Nullable(Of Integer)

    Public Overridable Property customer_teams As customer_teams
    Public Overridable Property projects As ICollection(Of projects) = New HashSet(Of projects)

End Class
