'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class projects
    Public Property id As Integer
    Public Property customer_id As Nullable(Of Integer)
    Public Property name As String
    Public Property order_number As String
    Public Property comment As String
    Public Property visible As Nullable(Of Short)
    Public Property fixed_rate As Double
    Public Property hourly_rate As Double
    Public Property budget As Nullable(Of Double)
    Public Property time_budget As Nullable(Of Integer)
    Public Property color As String

    Public Overridable Property activities As ICollection(Of activities) = New HashSet(Of activities)
    Public Overridable Property customers As customers
    Public Overridable Property project_teams As project_teams
    Public Overridable Property timesheet As ICollection(Of timesheet) = New HashSet(Of timesheet)

End Class
