'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class schedulerEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=schedulerEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property activities() As DbSet(Of activities)
    Public Overridable Property customer_teams() As DbSet(Of customer_teams)
    Public Overridable Property customers() As DbSet(Of customers)
    Public Overridable Property project_teams() As DbSet(Of project_teams)
    Public Overridable Property projects() As DbSet(Of projects)
    Public Overridable Property tags() As DbSet(Of tags)
    Public Overridable Property teams() As DbSet(Of teams)
    Public Overridable Property timesheet() As DbSet(Of timesheet)
    Public Overridable Property timesheet_tags() As DbSet(Of timesheet_tags)
    Public Overridable Property user_preferences() As DbSet(Of user_preferences)
    Public Overridable Property user_teams() As DbSet(Of user_teams)
    Public Overridable Property users() As DbSet(Of users)

End Class
