'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class teams
    Public Property id As Integer
    Public Property teamlead_id As Nullable(Of Integer)
    Public Property name As String

    Public Overridable Property customer_teams As ICollection(Of customer_teams) = New HashSet(Of customer_teams)
    Public Overridable Property project_teams As ICollection(Of project_teams) = New HashSet(Of project_teams)
    Public Overridable Property users As users
    Public Overridable Property user_teams As ICollection(Of user_teams) = New HashSet(Of user_teams)

End Class
