'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class timesheet
    Public Property id As Integer
    Public Property user_id As Nullable(Of Integer)
    Public Property activity_id As Nullable(Of Integer)
    Public Property project_id As Nullable(Of Integer)
    Public Property start_time As Nullable(Of Date)
    Public Property end_time As Date
    Public Property duration As Integer
    Public Property description As String
    Public Property rate As Nullable(Of Double)
    Public Property exported As Nullable(Of Short)
    Public Property fixed_rate As Double
    Public Property hourly_rate As Double

    Public Overridable Property activities As activities
    Public Overridable Property projects As projects
    Public Overridable Property timesheet_tags As timesheet_tags
    Public Overridable Property users As users

End Class
