'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class timesheet_tags
    Public Property timesheet_id As Integer
    Public Property tag_id As Nullable(Of Integer)

    Public Overridable Property tags As tags
    Public Overridable Property timesheet As timesheet

End Class
