'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class user_teams
    Public Property user_id As Integer
    Public Property team_id As Nullable(Of Integer)

    Public Overridable Property teams As teams
    Public Overridable Property users As users

End Class
