'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class users
    Public Property id As Integer
    Public Property username As String
    Public Property email As String
    Public Property enabled As Nullable(Of Short)
    Public Property salt As String
    Public Property password As String
    Public Property last_login As Nullable(Of Date)
    Public Property confirmation_token As String
    Public Property password_requested_at As Date
    Public Property roles As String
    Public Property [alias] As String
    Public Property registration_date As Date
    Public Property title As String
    Public Property avatar As String

    Public Overridable Property teams As ICollection(Of teams) = New HashSet(Of teams)
    Public Overridable Property timesheet As ICollection(Of timesheet) = New HashSet(Of timesheet)
    Public Overridable Property user_preferences As ICollection(Of user_preferences) = New HashSet(Of user_preferences)
    Public Overridable Property user_teams As user_teams

End Class
