//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scheduler_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customers()
        {
            this.customer_teams = new HashSet<customer_teams>();
            this.projects = new HashSet<projects>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string number { get; set; }
        public string comment { get; set; }
        public string company { get; set; }
        public string contact { get; set; }
        public string address { get; set; }
        public string country { get; set; }
        public string currency { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public Nullable<double> fixed_rate { get; set; }
        public Nullable<double> hourly_rate { get; set; }
        public double budget { get; set; }
        public int time_budget { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_teams> customer_teams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<projects> projects { get; set; }
    }
}
