//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scheduler_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_teams
    {
        public int id { get; set; }
        public Nullable<int> project_id { get; set; }
        public Nullable<int> team_id { get; set; }
    
        public virtual projects projects { get; set; }
        public virtual teams teams { get; set; }
    }
}
