//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scheduler_v2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class scheduler_v2Entities : DbContext
    {
        public scheduler_v2Entities()
            : base("name=scheduler_v2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activities> activities { get; set; }
        public virtual DbSet<customers> customers { get; set; }
        public virtual DbSet<projects> projects { get; set; }
        public virtual DbSet<tags> tags { get; set; }
        public virtual DbSet<teams> teams { get; set; }
        public virtual DbSet<timesheet> timesheet { get; set; }
        public virtual DbSet<user_preferences> user_preferences { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
