//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scheduler_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class timesheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public timesheet()
        {
            this.timesheet_tags = new HashSet<timesheet_tags>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public int activity_id { get; set; }
        public int project_id { get; set; }
        public System.DateTime start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public Nullable<int> duration { get; set; }
        public string description { get; set; }
        public Nullable<double> rate { get; set; }
        public Nullable<short> exported { get; set; }
        public Nullable<double> fixed_rate { get; set; }
        public Nullable<double> hourly_rate { get; set; }
    
        public virtual activities activities { get; set; }
        public virtual projects projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timesheet_tags> timesheet_tags { get; set; }
        public virtual users users { get; set; }
    }
}
